config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'sobre', to: 'static_page#sobre'
  get 'contato', to: 'static_page#contato'
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'


  resources :users, only: [:new, :create, :show]
  
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
  validates :name, presence: true, length: { maximum: 50 } 
  validates :password, presence: true, length: { maximum: 6 }
  validates :email, presence: true, length: { maximum: 255},
                                    format: { with: VALID_EMAIL_REGEX},
                                    uniqueness: { case_sensitive: true }
                                    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # redirencionar o usuario se show caso ele esteja logado!
  def new
    redirect_to user_path(current_user) if user_signed_in?
  end

  # aqui é da gem bcrypt que nos fornece essa funcao
  def create
    @user = User.find_by(email: params[:email].downcase)
    if @user && @user.authenticate(params[:password])
      sign_in @user
      redirect_to user_path(@user), notice: 'Login com sucesso'
    else
      redirect_to entrar_path, notice: "Senha ou email incorreto, ou em branco!"
    end
  end
  
#  destroy a session do user
  def destroy 
    sign_out
    redirect_to entrar_path, notice: 'Usuário Precisar se Logar'
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def sobre
  end

  def contato
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_users, only: [:index]
  before_action :get_user, only: [:index]

  def index; end

  def show; end

  def new 
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save
      redirect_to users_path, notice: 'User was successfully created'
    else  
      render :new
    end
  end

  private

  def get_users
    @users = User.all
  end

  def params_user
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

  def get_user
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portifolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/session.html.erb
<!doctype html>
<html lang="pt-BR" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Portifolio</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
   <%= stylesheet_link_tag  'application' %>
   <%= stylesheet_link_tag  'session' %>

  </head>
  <body class="d-flex flex-column h-100">
    
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
       <%=  link_to 'Portifolio', root_path, class:'navbar-brand'%>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
         
          <% unless user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Entrar', entrar_path, class:'nav-link active',aria_current:"page" %>
            </li>
          <% end %>

        </ul>
        
        <% if user_signed_in? %>
          <div class="dropdown">
            <a class="btn text-light btn-dark dropdown-toggle me-3 pe-3" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name %>
            </a>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              
              <li><a class="dropdown-item" href="#">Sobre</a></li>
              <li><a class="dropdown-item" href="#">Contato</a></li>
              <li>
                <%= link_to 'Sair', sair_path, method: :delete, class:"dropdown-item"%>
              </li>
            </ul>
          </div>
        <% end %>

      </div>
    </div>
  </nav>
</header>

<!-- Begin page content -->
<main class="flex-shrink-0">
  <div class="container">
    <%= yield %>
  </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
  <div class="container text-center">
    <span class="text-muted">Portalegre-RN <%= Date.today %></span>
  </div>
</footer>
   
  
  <%= javascript_include_tag 'application'%>
  <%= javascript_include_tag 'session' %>

  <% if notice %>
        <%= javascript_tag do %>
                $.bootstrapGrowl('<%= notice %>', {
                    type: 'success', // (null, 'info', 'danger', 'success')
                    align: 'right', // ('left', 'right', or 'center')
                    allow_dismiss: true, // If true then will display a cross to close the popup.
                    stackup_spacing: 10 // spacing between consecutively stacked growls.
                });
        <% end %>
   <% end %>

  </body>
</html>

app/views/layouts/sessions.html.erb
<!doctype html>
<html lang="pt-BR" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Portifolio</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
   <%= stylesheet_link_tag  'application' %>
   <%= stylesheet_link_tag  'sessions' %>

  </head>
  <body class="d-flex flex-column h-100">
    
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
       <%=  link_to 'Portifolio', root_path, class:'navbar-brand'%>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
         
          <% unless user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Entrar', entrar_path, class:'nav-link active',aria_current:"page" %>
            </li>
          <% end %>

        </ul>
        
        <% if user_signed_in? %>
          <div class="dropdown">
            <a class="btn text-light btn-dark dropdown-toggle me-3 pe-3" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
               Bem-vindo <%= current_user.name %>
            </a>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              
              <li><a class="dropdown-item" href="#">Sobre</a></li>
              <li><a class="dropdown-item" href="#">Contato</a></li>
              <hr/>
              <li>
                <%= link_to 'Sair', sair_path, method: :delete, class:"dropdown-item"%>
              </li>
            </ul>
          </div>
        <% end %>

      </div>
    </div>
  </nav>
</header>

<!-- Begin page content -->
<main class="flex-shrink-0">
  <div class="container">
    <%= yield %>
  </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
  <div class="container text-center">
    <span class="text-muted">Portalegre-RN <%= Date.today %></span>
  </div>
</footer>
   
  
  <%= javascript_include_tag 'application'%>
  <%= javascript_include_tag 'sessions' %>

  <% if notice %>
        <%= javascript_tag do %>
                $.bootstrapGrowl('<%= notice %>', {
                    type: 'success', // (null, 'info', 'danger', 'success')
                    align: 'right', // ('left', 'right', or 'center')
                    allow_dismiss: true, // If true then will display a cross to close the popup.
                    stackup_spacing: 10 // spacing between consecutively stacked growls.
                });
        <% end %>
   <% end %>

  </body>
</html>

app/views/layouts/users.html.erb
<!doctype html>
<html lang="pt-BR" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Portifolio</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
   <%= stylesheet_link_tag  'application' %>
   <%= stylesheet_link_tag  'users' %>

  </head>
  <body class="d-flex flex-column h-100">
    
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <%=  link_to 'Portifolio', root_path, class:'navbar-brand'%>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
         
          <% unless user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Entrar', entrar_path, class:'nav-link active',aria_current:"page" %>
            </li>
          <% end %>

        </ul>
        
        <% if user_signed_in? %>
          <div class="dropdown">
            <a class="btn text-light btn-dark dropdown-toggle me-3 pe-3" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                Bem-vindo <%= current_user.name %>
            </a>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              
              <li><a class="dropdown-item" href="#">Sobre</a></li>
              <li><a class="dropdown-item" href="#">Contato</a></li>
              <hr/>
              <li>
                <%= link_to 'Sair', sair_path, method: :delete, class:"dropdown-item"%>
              </li>
            </ul>
          </div>
        <% end %>

      </div>
    </div>
  </nav>
</header>

<!-- Begin page content -->
<main class="flex-shrink-0">
  <div class="container">
    <%= yield %>
  </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
  <div class="container text-center">
    <span class="text-muted">Portalegre-RN <%= Date.today %></span>
  </div>
</footer>
   
  
  <%= javascript_include_tag 'application'%>
  <%= javascript_include_tag 'users' %>

  <% if notice %>
        <%= javascript_tag do %>
                $.bootstrapGrowl('<%= notice %>', {
                    type: 'success', // (null, 'info', 'danger', 'success')
                    align: 'right', // ('left', 'right', or 'center')
                    allow_dismiss: true, // If true then will display a cross to close the popup.
                    stackup_spacing: 10 // spacing between consecutively stacked growls.
                });
        <% end %>
   <% end %>

  </body>
</html>

app/views/layouts/welcome.html.erb
<!doctype html>
<html lang="pt-BR" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Portifolio</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
   <%= stylesheet_link_tag  'application' %>
   <%= stylesheet_link_tag  'welcome' %>
   
  </head>
  <body class="d-flex flex-column h-100">
    
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <%=  link_to 'Portifolio', root_path, class:'navbar-brand'%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
         
          <% unless user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Entrar', entrar_path, class:'nav-link active',aria_current:"page" %>
            </li>
          <% end %>

        </ul>
        
        <% if user_signed_in? %>
          <div class="dropdown">
            <a class="btn text-light btn-dark dropdown-toggle me-3 pe-3" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              Bem-vindo <%= current_user.name %>
            </a>

            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              
              <li><a class="dropdown-item" href="#">Sobre</a></li>
              <li><a class="dropdown-item" href="#">Contato</a></li>
              <hr/>
              <li>
                <%= link_to 'Sair', sair_path, method: :delete, class:"dropdown-item"%>
              </li>
            </ul>
          </div>
        <% end %>

      </div>
    </div>
  </nav>
</header>

<!-- Begin page content -->
<main class="flex-shrink-0">
  <div class="container">
    <%= yield %>
  </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
  <div class="container text-center">
    <span class="text-muted">Portalegre-RN <%= Date.today %></span>
  </div>
</footer>
  
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'welcome' %>
  
  <% if notice %>
        <%= javascript_tag do %>
                $.bootstrapGrowl('<%= notice %>', {
                    type: 'success', // (null, 'info', 'danger', 'success')
                    align: 'right', // ('left', 'right', or 'center')
                    allow_dismiss: true, // If true then will display a cross to close the popup.
                    stackup_spacing: 10 // spacing between consecutively stacked growls.
                });
        <% end %>
   <% end %>

  </body>
</html>

app/views/session/shared/_form.html.erb
<div class="container my-2 px-4 py-2">
    <header class="d-flex justify-content-center py-3">
     <h2> Faça seu Login!</h2>
    </header>

    <%= form_with(model: @user, local: true) do |form| %>
        <% if @user.errors.any? %>
                <div class="alert alert-danger alert-dismissable" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <ul>
                        
                        <% @user.errors.full_messages.each do |error| %>
                            <li> <%= error %> </li>
                        <% end %>
                    </ul>
                </div>
        <% end %>

        <div class="mb-3">
        <%= form.label :email, class:"form-label", id:"exampleFormControl"%>
            <%= form.text_field :email, class:"form-control", for:"exampleFormControlInput1", placeholder:'ex: teste@teste.com' %>
        </div>

        <div class="mb-3">
        <%= form.label :password, class:"form-label", id:"exampleFormControl"%>
        <%= form.text_field :password, class:"form-control", for:"exampleFormControlInput1", placeholder:'Digite sua Senha' %>
        </div>

        <%= form.submit "Login", class:"btn btn-success"%>
    <% end %>
</div>

app/views/static_page/contato.html.erb
<h1> Contato </h1>

app/views/static_page/sobre.html.erb
<h1> Sobre </h1>

app/views/users/new.html.erb
<%= render partial: 'users/shared/form', locals: { message: 'Cadastro' }%>

app/views/users/shared/_form.html.erb
<div class="container my-1 px-3">
    <header class="d-flex justify-content-center py-2">
        <h2> Cadastre-se </h2>
    </header>

    <%= form_with(model: @user, local: true) do |form| %>
        <% if @user.errors.any? %>
                <div class="alert alert-danger alert-dismissable" role="alert">
                    <ul>
                        
                        <% @user.errors.full_messages.each do |error| %>
                            <li> <%= error %> </li>
                        <% end %>
                    </ul>
                </div>
        <% end %>

        <div class="mb-3">
        <%= form.label :email, class:"form-label", id:"exampleFormControl"%>
            <%= form.text_field :email, class:"form-control", for:"exampleFormControlInput1", placeholder:'ex: teste@teste.com' %>
        </div>

        <div class="mb-3">
        <%= form.label :name, class:"form-label", id:"exampleFormControl"%>
            <%= form.text_field :name, class:"form-control", for:"exampleFormControlInput1", placeholder:'Digite seu nome' %>
        </div>

        <div class="mb-3">
        <%= form.label :password, class:"form-label", id:"exampleFormControl"%>
        <%= form.text_field :password, class:"form-control", for:"exampleFormControlInput1", placeholder:'Digite sua Senha' %>
        </div>

        <div class="mb-3">
        <%= form.label :password_confirmation, class:"form-label", id:"exampleFormControl"%>
        <%= form.text_field :password_confirmation, class:"form-control", for:"exampleFormControlInput1", placeholder:'Confirme sua senha' %>
        </div>

        <%= form.submit "new User", class:"btn btn-success my-2"%>
    <% end %>
</div>

app/views/users/show.html.erb
<h1> <%= current_user.name %> </h1>
   
 

app/views/welcome/index.html.erb
<div class="bg-dark bg-gradient p-5 my-5 rounded">
    <h1 class=" text-light ">Bem-Vindo</h1>
    <p class="lead text-light">
     Esse portifólo é para autenticar usuários e cadastra a categoria do seu emprego (se ele trabalhar CLT ou INFORMAL). E ainda o usuários tem a parte de contato!
    </p>
    <%= link_to 'Cadastrar Usuário', new_user_path, class:'btn btn-lg btn-secondary'%>
</div>